[[project]]
    name = "MarriageBot"
    github = "https://github.com/4Kaylum/MarriageBot"
    website = "https://marriagebot.xyz"
    discord = "https://discord.gg/sWVgbPB"
    description = """
    MarriageBot is a bot made for the online chat service Discord to allow users to build a fake family with each other.
    MarriageBot handles hundreds of thousands of concurrent users, including async practises, an integrated website for settings, PayPal IPN for giving out user perks, and a whole lot of other data.
    """
    built_with = "Python3, asyncio, aiohttp, PostgreSQL, Redis"

[[project]]
    name = "Synergy"
    github = "https://github.com/4Kaylum/Synergy"
    website = "https://synergy.callumb.co.uk"
    discord = "https://discord.gg/sWVgbPB"
    description = """
    Synergy is a highly customisable Discord bot built around putting user ideas first. The concept for the bot is quite simple - users can specify commands that they can run on their Discord servers, and they can specify responses for those commands. From there, the goal was just to make everything as fluid as possible. Users are able to set up commands; restrict them to specific channels on their guild; restrict things down to roles - all of this configurable on the website.
    """
    built_with = "Python3, asyncio, aiohttp, PostgreSQL, Jinja2, Nginx"


[[project]]
    name = "TheDogAPI"
    github = "https://github.com/4Kaylum/TheDogAPI"
    website = ""
    discord = ""
    description = """
    Back when there was a gap in the market for APIs of dog images, I decided to take matters into my own hands and build my own. I downloaded a bunch of dog pictures from the Google Open Images database, and then threw them all up in the form of an API. The site is gone now, as is that gap in the market, but I'm proud of what I'd made for that year I had it on the internet.
    """
    built_with = "PHP, MySQL"
