[database]
    user = "voxelfox"
    password = ""
    database = "voxelfox"
    host = "127.0.0.1"
    port = 5432
    enabled = true

[paypal_item_webhooks."MarriageBot Gold"]
    authorization = ""  # The token that we include with the webhook so we know it's from us
    webhook_url = "https://marriagebot.xyz/webhooks/voxel_fox/purchase"  # The URL that we want to ping
    receiver_email = "billing@voxelfox.co.uk"  # The email that the PayPal account is set up with

[[topgg_bot_webhooks]]
    bot_id = 1
    authorization = "0"
    webhook_url = "https://marriagebot.xyz/webhooks/voxel_fox/topgg_vote_added"
